<?php

namespace BackendBundle\Repository;

/**
 * DatabaseVersion
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatabaseVersion extends \Doctrine\ORM\EntityRepository
{
}
