<?php

namespace BackendBundle\Repository;

/**
 * UserCompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCompanyRepository extends \Doctrine\ORM\EntityRepository
{
}
